[project]
name = "most-basic"
version = "0.1.0"
description = "Minimal MCP echo server/client example (works with mcp==1.5.0)"
authors = ["curtis@serverascode.com"]
requires-python = ">=3.10"
dependencies = [
    "mcp==1.5.0",
    "requests"
]