name: Test

# version 1

on:
  push:
    branches: [main]
    paths:
      - "examples/**"
      - "raillock/**"
      - "tests/**"
      - ".github/workflows/**"
      - "Makefile"
      - "pyproject.toml"
      - "setup.py"
      - "uv.lock"
  pull_request:
    branches: [main]
    paths:
      - "examples/**"
      - "raillock/**"
      - "tests/**"
      - ".github/workflows/**"
      - "Makefile"
      - "pyproject.toml"
      - "setup.py"
      - "uv.lock"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment for main project
        run: uv venv .venv --python 3.11

      - name: Set up dependencies with uv
        run: uv sync --dev

      - name: "Debug: pip show mcp"
        run: uv run pip show mcp || echo 'mcp NOT installed'

      - name: "Debug: List installed packages in main venv"
        run: uv pip list

      - name: Run tests
        run: make test
